services:
  - type: web
    name: lako
    env: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        value: https://emsmhgfzmgnpadpremkq.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtc21oZ2Z6bWducGFkcHJlbWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0NTIxNjgsImV4cCI6MjA5MjAyODE2OH0.h_f7FY60hNyYtVtvftUDXMuR2ybmZgiMZcnIyyeRkFE
      - key: BASE_URL
        value: https://lako.onrender.com
      - key: APP_NAME
        value: Lako
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: RENDER
        value: "true"